### ISSUE TITLE
 Exception while writing to stream - Postgresql

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#130]
This happens with idle connection in both Pisces and Hydromet tools:
to reproduce:
 1)  Connect Pisces or Hydromet tools to postgreql
 2) wait 1 hour
 3) try another database operation.

This started to happen with an upgraded Npgsq driver.  Possible solutions may be connection string option, or some type of ping/keep alive method call?

pgsql.NpgsqlException (0x80004005): Exception while writing to stream ---> System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at Npgsql.WriteBuffer.Flush()
   at Reclamation.Core.PostgreSQL.Table(String tableName, String sql, Boolean AcceptChangesDuringFill)
   at Reclamation.Core.PostgreSQL.Table(String tableName, String sql)
   at Reclamation.Core.PostgreSQL.TableExists(String tableName)
   at Reclamation.TimeSeries.TimeSeriesDatabase.InitDatabaseSettings(BasicDBServer server)
   at Reclamation.TimeSeries.TimeSeriesDatabase..ctor(BasicDBServer server, LookupOption lookup, Boolean readOnly)
   at HydrometTools.Database.DB()

**Comment by tjrocha** [comment]
Should we check for an active connection to the remote host before performing a DB operation and if the connection has been closed for any reason then bring up the log-in UI. Would this introduce too much overhead? Something like:

`if (!connection.Open)`
`{ logInForm.Show }`

**Comment by ktarbet** [comment]
I looked at the Npsql documentation and there is a feature that can ping the server on a schedule to keep alive.  However,  yesterdays  5f42226 update seem to be working so far.  I left Pisces on overnight and the error did *not* occur when resuming this morning.

**Comment by ktarbet** [comment]
5f42226 update continues to work -- closing.
