### ISSUE TITLE
BulkImportDirectory fails with special characters in filename/scenario

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#93]
To reproduce:
import file like this (Using Tools-Bulk Import Directory)
CSIRO-Mk3-6-0_RCP45_MACA_VIC_P1-PARI-biascorrected.csv

SQL logic error or missing database
near "-": syntax error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Reclamation.Core.SQLiteServer.RunSqlCommand(String sql, String SqlConnString) in c:\Users\KTarbet\Documents\project\Pisces\Core\SQLiteServer.cs:line 570
Error running Create Table CSIRO-Mk3-6-0_RCP45_MACA_VIC_P1-PARI-biascorrected_streamflow-provisional_0.5( datetime DateTime primary key, value float )
11/15/2016 6:34:06 PM: SQL logic error or missing database
near "-": syntax error

SQLite fails with some tablenames
http://stackoverflow.com/questions/3694276/what-are-valid-table-names-in-sqlite

**Comment by ktarbet** [comment]
If we wrap the tablename in brackets [tablename] that will solve the create table issue.  However, that may create other issues when reading / writing to the table.

In this example replacing '-' with '_' seems safe if that will be an acceptable change of the scenario name?

TimeSeriesDatabase has a SafeTableName() method that can do this.

``` 
public static string SafeTableName(string tableName)
        {
            string rval = Regex.Replace(tableName, @"[^A-Za-z0-9_]", "_").ToLower();
            // starts with letter
            if (rval.Length > 0)
            {
                if (!Char.IsLetter(rval, 0))
                    rval = "ts_" + rval;
            }
            return rval;
        }
```

**Comment by blounsbury** [comment]
BasicDBServer is already wrapping tablenames with spaces with brackets. Would a '-' cause more trouble than a space you think? If so, then I assume a '_' would be acceptable but I'm not sure I know the whole process, @jcuhaciyan might have a better idea.

```
public virtual string PortableTableName(string tableName)
{
    var rval = tableName;
    if( tableName.Trim().IndexOf(" ") >= 0)
    {
        rval = "[" + tableName + "]";
    }
    return rval;
}
```
